added cert check to c

diff --git a/bin/c b/bin/c
--- a/bin/c
+++ b/bin/c
@@ -79,6 +79,15 @@ fi
 
 echo PWD is `pwd`
 
+for i in anontion.key ssl/www_anontion_com.ca-bundle ssl/www_anontion_com.crt
+do
+  if [ ! -f "keys/${i}" ]
+  then
+    echo "mandatory keys file keys/${i} missing"
+    exit 1
+  fi
+done
+
 echo running docker build --no-cache --rm -f "$DOCKER_FILE"  --build-arg "ANONTION_DOCKER_GITUSER=$ANONTION_DOCKER_GITUSER" \
        --build-arg "ANONTION_SERVER_USER=$ANONTION_SERVER_USER" \
        --build-arg "ANONTION_SERVER_PASSWORD=$ANONTION_SERVER_PASSWORD" \
