updates tiday, added tomcat10, net-tools. apache2

diff --git a/src/main/docker/Dockerfile b/src/main/docker/Dockerfile
--- a/src/main/docker/Dockerfile
+++ b/src/main/docker/Dockerfile
@@ -1,12 +1,13 @@
-i# Dockerfile
+# Dockerfile
 
-# Use the official Ubuntu 24.04 base image
+# Use the official Ubuntu 22.04 base image
 FROM ubuntu:24.04
 
 # Environment
 ARG ANONTION_DOCKER_GITUSER=default_value
 ARG ANONTION_SERVER_USER=default_value
 ARG ANONTION_SERVER_PASSWORD=default_value
+ARG ANONTION_SERVER_REPO=default_value
 
 # Info
 RUN bash -c "echo starting using github user ${ANONTION_DOCKER_GITUSER} "
@@ -18,13 +19,23 @@ RUN apt-get update && \
 
 # Install necessary build tools for C++
 RUN apt-get update && \
-    DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-19-jdk && \
+    DEBIAN_FRONTEND=noninteractive apt-get install -y default-jdk && \
     rm -rf /var/lib/apt/lists/*
 
 # Install tomcat
 RUN apt-get update && \
-    DEBIAN_FRONTEND=noninteractive apt-get install -y tomcat9 && \
+    DEBIAN_FRONTEND=noninteractive apt-get install -y tomcat10 && \
     rm -rf /var/lib/apt/lists/*
+
+# Install net-tools
+RUN apt-get update && \
+    DEBIAN_FRONTEND=noninteractive apt-get install -y net-tools && \
+    rm -rf /var/lib/apt/lists/*
+
+# Install apache2
+RUN apt-get update && \
+    DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 && \
+    rm -rf /var/lib/apt/lists/* \
 
 # Install other named tools
 RUN apt-get update && \
@@ -39,10 +50,10 @@ RUN apt-get update && \
 WORKDIR /usr/local/src
 
 # Clone HU_anontion-server
-RUN git clone https://github.com/${ANONTION_DOCKER_GITUSER}/HU_anontion-server.git
+RUN git clone https://github.com/${ANONTION_DOCKER_GITUSER}/${ANONTION_SERVER_REPO}.git
 
 # Set the working directory
-# WORKDIR /usr/local/src/HU_anontion-server/.../webapp/WEB-INF
+# WORKDIR /usr/local/src/${ANONTION_SERVER_REPO}/.../webapp/WEB-INF
 
 # Update web.xml with user and password
 # RUN sed -i.bak "s/__________USER_REPLACE_ME__________/${ANONTION_SERVER_USER}/" web.xml
@@ -64,7 +75,7 @@ RUN git clone https://github.com/${ANONTION_DOCKER_GITUSER}/HU_anontion-server.g
 # RUN cat server-public.key
 
 # Set the working directory
-WORKDIR /usr/local/src/HU_anontion-server/bin
+WORKDIR /usr/local/src/${ANONTION_SERVER_REPO}/bin
 
 # Build
 RUN ./c
@@ -73,18 +84,18 @@ RUN ./c
 # RUN if [ ! -e /usr/local/src/dynip-server/dynip-server/build/libs/ipserver.war ]; then echo "missing war file "; exit 1; fi
 
 # Copy war into place
-# RUN cp /usr/local/src/dynip-server/dynip-server/build/libs/ipserver.war /var/lib/tomcat9/webapps/ipserver.war
+# RUN cp /usr/local/src/dynip-server/dynip-server/build/libs/ipserver.war /var/lib/tomcat10/webapps/ipserver.war
 
 # Check war copy
-# RUN if [ ! -f /var/lib/tomcat9/webapps/ipserver.war ]; then echo "missing war copy "; exit 1; fi
+# RUN if [ ! -f /var/lib/tomcat10/webapps/ipserver.war ]; then echo "missing war copy "; exit 1; fi
 
 # Config
-# RUN cp -f /var/lib/tomcat9/conf/server.xml /var/lib/tomcat9/conf/server.xml.bak
+RUN cp -f /var/lib/tomcat10/conf/server.xml /var/lib/tomcat10/conf/server.xml.bak
 
 # Check config
-# RUN if [ ! -f /var/lib/tomcat9/conf/server.xml ]; then echo "missing server.xml "; exit 1; fi
+RUN if [ ! -f /var/lib/tomcat10/conf/server.xml ]; then echo "missing server.xml "; exit 1; fi
 
-# RUN if [ ! -f /var/lib/tomcat9/conf/server.xml.bak ]; then echo "missing server.xml.bak "; exit 1; fi
+RUN if [ ! -f /var/lib/tomcat10/conf/server.xml.bak ]; then echo "missing server.xml.bak "; exit 1; fi
 
 # Customise config
 # RUN awk 'BEGIN { found = 0; RS = "\0"; ORS = ""; }                         \
@@ -92,10 +103,10 @@ RUN ./c
 #         sub(/<\/Host>[[:space:]\n]*<\/Engine>/, "<Context docBase=\"ipserver\" path=\"/iserver\" reloadable=\"true\" /></Host></Engine>");  \
 #         found = 1;                                                        \
 #     }                                                                     \
-#     { print; }' /var/lib/tomcat9/conf/server.xml.bak > /var/lib/tomcat9/conf/server.xml
+#     { print; }' /var/lib/tomcat10/conf/server.xml.bak > /var/lib/tomcat10/conf/server.xml
      
 # Empty default app 
-# RUN echo "." >  /var/lib/tomcat9/webapps/ROOT/index.html
+# RUN echo "." >  /var/lib/tomcat10/webapps/ROOT/index.html
 
 # Expose the default Tomcat port
 EXPOSE 80
@@ -103,12 +114,15 @@ EXPOSE 443
 EXPOSE 8080
 
 # Set CATALINA_BASE and update PATH to include catalina.sh
-ENV CATALINA_BASE /var/lib/tomcat9
-ENV CATALINA_HOME /usr/share/tomcat9
+ENV CATALINA_BASE /var/lib/tomcat10
+ENV CATALINA_HOME /usr/share/tomcat10
 ENV PATH $CATALINA_HOME/bin:$PATH
 
-WORKDIR /var/lib/tomcat9/
+WORKDIR /var/lib/tomcat10/
 
-# Start Tomcat when the container starts
+# start apache
+CMD service apache2 start  
+
+# start tomcat when the container starts
 CMD ["catalina.sh", "run"]
 
